[Town] # faction name
  min_num = 7 # minimum number in this faction
  weight = 0.4 # weight for any
  [Town.Investigative] # category name
    min_num = 1 # min number in category
    weight = nan # not yet implemented
    [Town.Investigative.roles.Sheriff] # role name
      max_num = inf # max number of this role
      weight = nan # not yet implemented
    [Town.Investigative.roles.Psychic]
      max_num = inf
      weight = nan
    [Town.Investigative.roles.Lookout]
      max_num = inf
      weight = nan
    [Town.Investigative.roles.Tracker]
      max_num = inf
      weight = nan
  [Town.Protective]
    min = 1
    weight = nan
    [Town.Protective.roles.Bodyguard]
      max_num = inf
      weight = nan
    [Town.Protective.roles.Doctor]
      max_num = inf
      weight = nan
  [Town.Killing]
    min = 1
    weight = nan
    [Town.Killing.Vigilante]
      max_num = inf
      weight = nan
    [Town.Killing.Veteran]
      max_num = inf
      weight = nan
  [Town.Necrotic]
    min = 1
    weight = nan
    [Town.Necrotic.roles.Medium]
      max_num = 1
      weight = nan
    [Town.Necrotic.roles.Necromancer]
      max_num = 1
      weight = nan
  [Town.Support]
    min = 1
    weight = nan
    [Town.Support.roles.Swapper]
      max_num = 1
      weight = nan
    [Town.Support.roles.Escort]
      max_num = inf
      weight = nan
    [Town.Support.roles.Admirer]
      max_num = inf
      weight = nan
    [Town.Support.roles.Mayor]
      max_num = inf
      weight = nan

["Neutral Killing"]
  min_num = 1
  weight = 0
  ["Neutral Killing".All]
    ["Neutral Killing".All.roles."Serial Killer"]
      max_num = 1
      weight = nan
    ["Neutral Killing".All.roles.Cannibal]
      max_num = 1
      weight = nan
    ["Neutral Killing".All.roles.Arsonist]
      max_num = 1
      weight = nan
["Neutral Evil"]
  min_num = 1
  weight = 0.3
  ["Neutral Evil".All]
    ["Neutral Evil".All.roles.Jester]
      max_num = 1
      weight = nan
    ["Neutral Evil".All.roles.Executioner]
      max_num = 1
      weight = nan
[Mafia]
  min_num = 3
  weight = 0.3
  isHoncho = true # is there a Head Honcho?
  [Mafia.All]
    [Mafia.All.roles.Consort]
      max_num = 1
      weight = nan
    [Mafia.All.roles.Consigliere]
      max_num = 1
      weight = nan
    [Mafia.All.roles.Ambusher]
      max_num = 1
      weight = nan
    [Mafia.All.roles.Magnate]
      max_num = 1
      weight = nan
    [Mafia.All.roles.Framer]
      max_num = 1
      weight = nan
[[Any]]
  min_num = 1
[[Drunk]]
  isDrunk = true # is there a drunk?
