[Town] # faction name
  min_num = 7 # minimum number in this faction
  weight = 0.5 # weight for any
  is_evil = false # is this faction evil?
  [Town.Investigative] # category name
    min_num = 1 # min number in category
    [Town.Investigative.roles.Sheriff] # role name
      max_num = inf # max number of this role
      blockable = true # can this role be blocked?
      action_priority = 5 # order of night actions. Lower is earlier; use 99 for no night action
    [Town.Investigative.roles.Psychic]
      max_num = inf
      blockable = false
      action_priority = 5
    [Town.Investigative.roles.Lookout]
      max_num = inf
      blockable = true
      action_priority = 9
    [Town.Investigative.roles.Tracker]
      max_num = inf
      blockable = true
      action_priority = 9
  [Town.Protective]
    min_num = 1
    [Town.Protective.roles.Bodyguard]
      max_num = inf
      blockable = true
      action_priority = 4
    [Town.Protective.roles.Doctor]
      max_num = inf
      blockable = true
      action_priority = 4
  [Town.Killing]
    min_num = 0
    [Town.Killing.roles.Vigilante]
      max_num = inf
      blockable = true
      action_priority = 6
    [Town.Killing.roles.Veteran]
      max_num = inf
      blockable = false
      action_priority = 0
  [Town.Necrotic]
    min_num = 0
    [Town.Necrotic.roles.Medium]
      max_num = 1
      blockable = false
      action_priority = 99
    [Town.Necrotic.roles.Necromancer]
      max_num = 1
      blockable = true
      action_priority = 4
  [Town.Support]
    min_num = 0
    [Town.Support.roles.Swapper]
      max_num = 1
      blockable = false
      action_priority = 1
    [Town.Support.roles.Escort]
      max_num = inf
      blockable = false
      action_priority = 2
    [Town.Support.roles.Admirer]
      max_num = 1
      blockable = true
      action_priority = 10
    [Town.Support.roles.Mayor]
      max_num = 1
      blockable = false
      action_priority = 99
["Neutral Killing"]
  min_num = 0
  weight = 0.0
  isEvil = true
  ["Neutral Killing".All]
  	min_num = 0
    ["Neutral Killing".All.roles."Serial Killer"]
      max_num = 1
      blockable = false
      action_priority = 6
    ["Neutral Killing".All.roles.Cannibal]
      max_num = 1
      blockable = true
      action_priority = 6
    ["Neutral Killing".All.roles.Arsonist]
    blockable = false
      max_num = 1
      action_priority = 6
["Neutral Evil"]
  min_num = 1
  weight = 0.3
  isEvil = true
  ["Neutral Evil".All]
    min_num = 0
    ["Neutral Evil".All.roles.Jester]
      max_num = 1
      blockable = false
      action_priority = 99
    ["Neutral Evil".All.roles.Executioner]
      max_num = 1
      blockable = false
      action_priority = 99
[Mafia]
  min_num = 2
  weight = 0.2
  isHoncho = false # is there a Head Honcho?
  isEvil = true
  [Mafia.All]
  min_num = 0
    [Mafia.All.roles.Consort]
      max_num = 1
      blockable = false
      action_priority = 2
    [Mafia.All.roles.Consigliere]
      max_num = 1
      blockable = true
      action_priority = 5
    [Mafia.All.roles.Ambusher]
      max_num = 1
      blockable = true
      action_priority = 3
    [Mafia.All.roles.Framer]
      max_num = 1
      blockable = true
      action_priority = 4
[Drunk]
  is_drunk = true # depricated
  drunk_num = 1 # must be integer greater than or equal to 0
  isEvil = false
  action_priority = 7